# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
parameters:
    jobNameSuffix: ''
    windowsImage: 'windows-2022-secure'
    macImage: 'macOS-latest'
    linuxImage: 'ubuntu-22.04-secure'

jobs:
    - job: 'build_all_windows${{ parameters.jobNameSuffix }}'
      pool:
          name: $(a11yInsightsPool)
          image: ${{ parameters.windowsImage }}
          os: windows
      steps:
          - template: ./install-node-prerequisites.yaml
          - script: yarn build:all
            displayName: build:all

    - job: 'build_all_mac${{ parameters.jobNameSuffix }}'
      pool:
          name: Azure Pipelines
          vmImage: ${{ parameters.macImage }}
          os: macOS
      steps:
          - template: ./install-node-prerequisites.yaml
          - script: yarn build:all
            displayName: build:all

    - job: 'build_all_linux${{ parameters.jobNameSuffix }}'
      pool:
          name: $(a11yInsightsPool)
          image: ${{ parameters.linuxImage }}
          os: linux
      steps:
          - template: ./install-node-prerequisites.yaml
          - script: yarn build:all
            displayName: build:all
