version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    version_requirement_updates: "increase_versions"
    default_labels:
      - "category: engineering"
      - "dependencies"
    commit_message:
      prefix: "chore"
      include_scope: true
    ignored_updates:
      - match:
          # We use webdriverio only indirectly via spectron; our direct
          # dependency on the package is only for the sake of typings, so
          # we stick to the major version of webdriverio used by spectron.
          #
          # The spectron issue tracking their update to v5 is
          # https://github.com/electron-userland/spectron/issues/349
          dependency_name: "webdriverio"
          version_requirement: ">=5.0.0"
      - match:
          # axe-core updates require enough extra validation
          # on false positives and breaking ai-web, so avoiding
          # dependabot auto-update for them like other deps.
          dependency_name: "axe-core"
      - match:
          # All electron builds are going to be manually updated
          # since our release builds use a non-standard Electron build with distribution-restricted media codecs stripped out
          dependency_name: "electron"
