# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
    jobNameSuffix: ''
    windowsImage: 'windows-2019'
    macImage: 'macOS-10.14'
    linuxImage: 'ubuntu-16.04'

jobs:
    - job: 'electron_e2e_tests_windows${{ parameters.jobNameSuffix }}'
      pool:
          vmImage: ${{ parameters.windowsImage }}
      steps:
          - template: ../install-node-prerequisites.yaml
          - template: ./electron-e2e-test-interactive.yaml
          - template: ./electron-e2e-publish-results.yaml

    - job: 'electron_e2e_tests_mac${{ parameters.jobNameSuffix }}'
      pool:
          vmImage: ${{ parameters.macImage }}
      steps:
          - template: ../install-node-prerequisites.yaml
          - template: ./electron-e2e-test-interactive.yaml
          - template: ./electron-e2e-publish-results.yaml

    - job: 'electron_e2e_tests_linux${{ parameters.jobNameSuffix }}'
      pool:
          vmImage: ${{ parameters.linuxImage }}
      steps:
          - template: ../install-node-prerequisites.yaml
          - template: ./unified-e2e-test-linux.yaml
          - template: ./electron-e2e-publish-results.yaml
